import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const read = (relative: string) => readFileSync(fileURLToPath(new URL(relative, import.meta.url)), 'utf8')
  .replace(/\r\n/g, '\n')

describe('dsh-work Client shell contract', () => {
  it('owns the standard settings child Slots and renders them inside the existing settings page', () => {
    const shell = read('../../../packages/dsh-work-shell/src/client/index.tsx')
    const settings = read('../views/agent/AgentSettings.tsx')

    expect(shell).toContain('new DshConversationBridge(ctx.sessions, ctx.inputTriggers)')
    expect(shell).toContain('registerToolConversationLocale(ctx.locale)')
    expect(shell).toContain("}, 'dsh-work shell slot tree')")
    expect(shell.indexOf("name: 'root'")).toBeLessThan(shell.indexOf("name: 'sidebar'"))
    expect(shell.indexOf("name: 'root'")).toBeLessThan(shell.indexOf("name: 'conversation'"))
    expect(shell.indexOf("name: 'root'")).toBeLessThan(shell.indexOf("name: 'settings.section'"))
    expect(shell).toContain("children: { 'settings.general.item': { kind: 'list', scope: 'root' } }")
    expect(shell).not.toContain("children: { 'settings.plugins.tab': { kind: 'list', scope: 'root' } }")
    expect(shell).toContain("'sidebar.footer.action': { kind: 'list', scope: 'root' }")
    expect(shell).toContain("[PRE_SESSION_ATTACHMENTS_SLOT]: { kind: 'list', scope: 'root' }")
    expect(shell).toContain("document.querySelector('[data-dsh-work-pre-session-attachments]')")
    expect(shell).toContain("renderSlot('sidebar.footer.action', { wide: true })")
    expect(shell).toContain("'conversation.session.header.actions': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("'conversation.session.header.utilities': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("'conversation.input.overlay': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("'conversation.composer': { kind: 'chain', scope: 'session' }")
    expect(shell).toContain("renderSlotChain(\n              'conversation.composer'")
    expect(shell).toContain('{ interactions: session.pending, session }')
    expect(shell).toContain('data-dsh-product-composer-resident')
    expect(shell).toContain("'conversation.input.dock': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("'conversation.composer.dock': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("'conversation.input.left': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("'conversation.input.right': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("'conversation.input.plan': { kind: 'single', scope: 'session' }")
    expect(shell).toContain("renderSlot('conversation.input.plan', { locked: session.removed })")
    expect(shell).toContain("'conversation.input.model': { kind: 'single', scope: 'session' }")
    expect(shell).toContain("renderSlot('conversation.input.model', { locked: session.removed })")
    expect(shell).toContain("'conversation.hero.workspace': { kind: 'single', scope: 'root' }")
    expect(shell).toContain("renderSlot('conversation.hero.workspace', {})")
    expect(shell).toContain("'conversation.hero.agentPreset': { kind: 'single', scope: 'root' }")
    expect(shell).toContain("renderSlot('conversation.hero.agentPreset', {})")
    expect(shell.indexOf('const heroWorkspace =')).toBeLessThan(
      shell.indexOf('if (!host || !sessionId || !session) return hero')
    )
    expect(shell).toContain('new DshWorkConversationService(ctx, {')
    expect(shell).toContain('new DshWorkProductActionsService(ctx, conversation)')
    expect(shell).toContain('new DshWorkProductAttachmentsService(ctx, conversation)')
    expect(shell).toContain('input: conversation.input')
    expect(shell).toContain('blocks: conversation.blocks')
    expect(shell).toContain('sessions: ctx.sessions')
    const conversationService = read('../../../packages/dsh-work-shell/src/client/ConversationService.ts')
    expect(conversationService).toContain("super(ctx, 'conversation')")
    expect(conversationService).toContain("this.session('send').prompt")
    expect(conversationService).toContain("this.session('updateQueue').updateQueue")
    expect(conversationService).toContain("this.session('cancel').cancel")
    expect(conversationService).toContain("this.session('loadOlder').loadOlder")
    expect(conversationService).toContain('private readonly sessions: DshWorkSessions')
    expect(conversationService).not.toContain('readonly #sessions')
    expect(conversationService).not.toContain('#session(')
    expect(shell).toContain("'conversation.chat.node': { kind: 'keyed', scope: 'session' }")
    expect(shell).toContain("entryKey: 'tool-call'")
    expect(shell).toContain('data-dsh-product-tool-call-resident')
    expect(shell).toContain("name: 'details'")
    expect(shell).toContain("'conversation.details.tool': { kind: 'single', scope: 'session' }")
    expect(shell).toContain("renderSlot('conversation.details.tool', { block, cwd }")
    expect(shell).toContain('conversation.selectToolCall(sessionId, callId)')
    expect(shell).toContain('layout.openDetails()')
    expect(shell).toContain('data-dsh-standard-tool-details')
    expect(shell).toContain('data-dsh-standard-tool-details-output')
    expect(shell).toContain('data-dsh-product-tool-details-fallback')
    expect(shell).toContain('if (hadSelection.current)')
    expect(shell).toContain("'conversation.chat.assistant-actions': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("renderSlot('conversation.chat.assistant-actions', { messageId })")
    expect(shell).toContain("'conversation.chat.turnTail': { kind: 'chain', scope: 'session' }")
    expect(shell).toContain("renderSlotChain('conversation.chat.turnTail', { turn, seq, openFile: conversation.openFile })")
    expect(shell).toContain("renderSlot('conversation.composer.dock'")
    expect(shell).toContain("renderSlot('conversation', {}, { only: 'dsh-work-conversation' })")
    expect(shell).not.toContain('productCommandSource')
    expect(shell).not.toContain('DSH_WORK_COMMANDS')
    const productActions = read('../../../packages/dsh-work-shell/src/client/ProductActionsService.ts')
    expect(productActions).toContain("super(ctx, 'dshWorkProductActions')")
    expect(productActions).toContain('this.conversation.runProductCommand(sessionId, name)')
    expect(productActions).not.toContain('readonly #conversation')
    const productCommands = read('../../../packages/dsh-client-product-commands/src/client/index.ts')
    expect(productCommands).toContain("export const inject = ['sessions', 'inputTriggers', 'locale', 'dshWorkProductActions']")
    expect(productCommands).toContain("name: 'dsh-work'")
    expect(productCommands).toContain("'slash/input-consume-token'")
    expect(productCommands).toContain('matchEnter: async (session, line, signal)')
    expect(productCommands).toContain('ctx.dshWorkProductActions.run(sessionId, name)')
    const productReferencesService = read('../../../packages/dsh-work-shell/src/client/ProductReferencesService.ts')
    expect(productReferencesService).toContain("super(ctx, 'dshWorkProductReferences')")
    expect(productReferencesService).toContain('this.conversation.listProductReferences(sessionId, kind, query)')
    expect(productReferencesService).not.toContain('readonly #conversation')
    const productReferences = read('../../../packages/dsh-client-product-references/src/client/index.ts')
    expect(productReferences).toContain("export const inject = ['inputTriggers', 'dshWorkProductReferences']")
    expect(productReferences).toContain("source(ctx, 'dsh-work-files', 'file', 10)")
    expect(productReferences).toContain("source(ctx, 'dsh-work-conversations', 'conversation', 20)")
    expect(productReferences).toContain("trigger: '@'")
    expect(productReferences).toContain('ctx.dshWorkProductReferences.list(session.sessionId, kind, query)')
    const productSearchModeService = read('../../../packages/dsh-work-shell/src/client/ProductSearchModeService.ts')
    expect(productSearchModeService).toContain("super(ctx, 'dshWorkProductSearchMode')")
    expect(productSearchModeService).toContain('this.conversation.cycleProductSearchMode(sessionId)')
    expect(productSearchModeService).not.toContain('readonly #conversation')
    const productSearchMode = read('../../../packages/dsh-client-product-search-mode/src/client/index.ts')
    expect(productSearchMode).toContain("export const inject = ['slots', 'locale', 'dshWorkProductSearchMode']")
    expect(productSearchMode).toContain("ctx.slots.inject('conversation.input.left'")
    expect(productSearchMode).toContain("id: 'dsh-work-search-mode'")
    expect(productSearchMode).toContain("'data-dsh-product-search-mode': true")
    const productWorkspacesService = read('../../../packages/dsh-work-shell/src/client/ProductWorkspacesService.ts')
    expect(productWorkspacesService).toContain("super(ctx, 'dshWorkProductWorkspaces')")
    expect(productWorkspacesService).toContain('this.conversation.selectProductWorkspace(id)')
    expect(productWorkspacesService).not.toContain('readonly #conversation')
    const productWorkspaces = read('../../../packages/dsh-client-product-workspaces/src/client/index.ts')
    expect(productWorkspaces).toContain("export const inject = ['slots', 'locale', 'dshWorkProductWorkspaces']")
    expect(productWorkspaces).toContain("ctx.slots.inject('conversation.hero.workspace'")
    expect(productWorkspaces).not.toContain("id: 'dsh-work-workspace-picker'")
    const productAttachmentsService = read('../../../packages/dsh-work-shell/src/client/ProductAttachmentsService.ts')
    expect(productAttachmentsService).toContain("super(ctx, 'dshWorkProductAttachments')")
    expect(productAttachmentsService).toContain('this.conversation.removeProductAttachment(sessionId, id)')
    const productAttachments = read('../../../packages/dsh-client-product-attachments/src/client/index.ts')
    expect(productAttachments).toContain("export const inject = ['slots', 'locale', 'dshWorkProductAttachments']")
    expect(productAttachments).toContain("ctx.slots.inject('conversation.input.dock'")
    expect(productAttachments).toContain("ctx.slots.inject('dsh-work.composer.pre-session'")
    expect(productAttachments).toContain('React.createElement(AttachmentRail')
    expect(shell).toContain("document.querySelector('[data-dsh-standard-details]')")
    expect(shell).toContain("renderSlot('details', {})")
    expect(settings).toContain('<DshSettingsSection id="general"')
    expect(settings).toContain('<DshSettingsSection id="models"')
    expect(settings).toContain('<DshSettingsSection id="plugins"')
    expect(read('../views/agent/AgentNav.tsx')).toContain('data-dsh-sidebar-footer-actions')
    const conversation = read('../views/agent/AgentConversation.tsx')
    const assistantContent = read('../views/agent/conversation/AssistantContent.tsx')
    const conversationCss = read('../views/agent/agent.module.scss')
    expect(conversation).toContain('data-dsh-session-header-actions')
    expect(conversation).toContain('data-dsh-session-header-utilities')
    expect(conversation).toContain('data-dsh-conversation-input-overlay')
    expect(conversation).toContain('conversation.trackInputTrigger')
    expect(conversation).toContain('conversation.arbitrateInputTrigger')
    expect(conversation).toContain('conversation.applyInputSpace')
    expect(conversation).toContain('conversation.submitOfficialInput')
    expect(conversation).toContain('const dshInputHandlersRef = useRef(dshInputHandlers)')
    expect(conversation).toContain('dshInputHandlersRef.current = dshInputHandlers')
    expect(conversation).toContain('runCommand: (name) => dshInputHandlersRef.current.runCommand?.(name)')
    expect(conversation).toContain('conversation.bindProductReferenceHandlers')
    expect(conversation).toContain('if (dshClientHost) {')
    expect(conversation).toContain('officialReferences={Boolean(dshClientHost)}')
    expect(conversation).toContain('conversation.trackInputTrigger(el.value, pos, { reserveLeadingSlash: false })')
    expect(conversation).toContain('conversation.bindProductSearchModeHandler(setSearchMode)')
    expect(conversation).toContain('conversation.updateProductSearchMode(searchMode)')
    expect(conversation).toContain('conversation.bindProductWorkspaceHandlers')
    expect(conversation).toContain('conversation.updateProductWorkspaces')
    expect(conversation).toContain('conversation.updateProductAttachments(productAttachments)')
    expect(conversation).toContain('conversation.bindProductAttachmentHandlers')
    expect(conversation).toContain('}, [dshClientHost])')
    expect(conversation).toContain('conversation.subscribeSessionState')
    expect(conversation).toContain('conversation.getSessionStateSnapshot')
    expect(conversation).toContain('applyDshProjectedSessionState(officialSessionState)')
    expect(conversation).toContain('if (dshClientHost) return')
    expect(conversation).toContain('data-dsh-command-hint')
    expect(conversation).toContain('reserveLeadingSlash: !dshClientHost && slashMatch !== null')
    expect(conversation).toContain('if (slashMatch && !dshClientHost)')
    expect(conversation).toContain("data-active={officialInputMenuActive ? 'true' : undefined}")
    expect(conversation).toContain('data-dsh-conversation-input-dock')
    expect(conversation).toContain('data-dsh-conversation-composer-dock')
    expect(conversation).toContain('data-dsh-conversation-composer-takeover')
    expect(conversationCss).toContain('.composerTakeover:has([data-dsh-standard-conversation-composer-chain])')
    expect(assistantContent).toContain('data-dsh-tool-call-takeover={toolCall.callId}')
    expect(assistantContent).toContain('host.conversation.registerToolCall(toolCall)')
    expect(conversationCss).toContain('.toolCallTakeover:has([data-dsh-standard-tool-call-node])')
    expect(conversation).toContain('data-dsh-conversation-input-left')
    expect(conversation).toContain('data-dsh-conversation-input-right')
    expect(conversation).toContain('data-dsh-conversation-input-plan')
    expect(conversation).toContain('dshClientHost ? undefined : collaborationModeRef.current')
    expect(conversation).toContain('data-dsh-conversation-input-model')
    expect(conversation).toContain('dshClientHost ? undefined : modelRuntime?.modelId')
    expect(conversation).toContain('data-dsh-conversation-hero-agent-preset')
    expect(conversation).toContain('officialComposerBlock?.reason')
    expect(conversation).toContain('disabled={Boolean(officialComposerBlock)}')
    expect(read('../views/agent/conversation/ConversationTurns.tsx')).toContain('data-dsh-assistant-message-id={message.dshMessageId}')
    expect(read('../views/agent/conversation/ConversationTurns.tsx')).toContain('data-dsh-closing-seq={message.dshClosingSeq}')
    expect(read('../views/agent/conversation/ConversationTurns.tsx')).toContain('data-dsh-produced-paths={JSON.stringify(dshProducedPaths)}')
    const agentShell = read('../views/agent/AgentShell.tsx')
    expect(agentShell).toContain('data-dsh-standard-details')
    expect(agentShell).toContain('setStandardDetailsOpen(opening)')
    expect(agentShell).toContain('hidden={standardDetailsOpen}')
    expect(read('../../../packages/dsh-work-shell/cordis.patch.yml')).toMatch(/id: ui-sidebar\n\s+disabled: true/)
    expect(read('../../../packages/dsh-work-shell/cordis.patch.yml')).toMatch(/id: ui-conversation\n\s+disabled: true/)
    expect(read('../../../packages/dsh-work-shell/package.json')).toContain('"@deepseek-ai/dsh-client-ui-tool"')
    expect(read('../../../packages/dsh-client-product-commands/cordis.patch.yml')).toContain("name: '@deepseek-ai/dsh-client-product-commands'")
    expect(read('../../../packages/dsh-client-product-references/cordis.patch.yml')).toContain("name: '@deepseek-ai/dsh-client-product-references'")
    expect(read('../../../packages/dsh-client-product-search-mode/cordis.patch.yml')).toContain("name: '@deepseek-ai/dsh-client-product-search-mode'")
    const productWorkspacesPatch = read('../../../packages/dsh-client-product-workspaces/cordis.patch.yml')
    expect(productWorkspacesPatch).toMatch(/id: ui-workspace\n\s+disabled: true/)
    expect(productWorkspacesPatch).toContain("name: '@deepseek-ai/dsh-client-product-workspaces'")
    expect(read('../../../packages/dsh-client-product-attachments/cordis.patch.yml')).toContain("name: '@deepseek-ai/dsh-client-product-attachments'")
  })

  it('uses DSH Theme and Locale snapshots in the formal Client runtime', () => {
    const shell = read('../../../packages/dsh-work-shell/src/client/index.tsx')
    const host = read('./DshClientHost.tsx')
    const page = read('../views/agent/index.tsx')

    expect(shell).toContain("import { createDshThemePresenter }")
    expect(shell).toContain('const presenter = createDshThemePresenter(document)')
    expect(shell).toContain('presenter.present(snapshot)')
    expect(shell).toContain('presenter.dispose()')
    expect(shell).not.toContain('function applyTheme(')
    expect(host).toContain('themeSnapshot: ThemeSnapshot')
    expect(host).toContain('localeSnapshot: LocaleSnapshot')
    expect(page).toContain('dshClientHost?.themeSnapshot.preference')
    expect(page).toContain('dshClientHost?.themeSnapshot.active.colorScheme')
    expect(page).toContain('dshClientHost?.localeSnapshot.active')
    expect(page).toContain('if (!dshClientHost) localStorage.setItem')
  })

  it('lets rendered overlay children receive pointer input', () => {
    const css = read('./DshClientHost.module.scss')
    const conversationCss = read('../views/agent/agent.module.scss')

    expect(css).toContain('pointer-events: none')
    expect(css).toMatch(/> \* \{\s*pointer-events: auto/)
    expect(conversationCss).toContain(".composerInputOverlay:not([data-active='true'])")
    expect(conversationCss).toContain('pointer-events: none')
  })
})
