import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const read = (relative: string) => readFileSync(fileURLToPath(new URL(relative, import.meta.url)), 'utf8')
  .replace(/\r\n/g, '\n')

describe('dsh-work Client shell contract', () => {
  it('owns the standard settings child Slots and renders them inside the existing settings page', () => {
    const shell = read('../../../packages/dsh-work-shell/src/client/index.tsx')
    const settings = read('../views/agent/AgentSettings.tsx')

    expect(shell).toContain("children: { 'settings.general.item': { kind: 'list', scope: 'root' } }")
    expect(shell).not.toContain("children: { 'settings.plugins.tab': { kind: 'list', scope: 'root' } }")
    expect(shell).toContain("'sidebar.footer.action': { kind: 'list', scope: 'root' }")
    expect(shell).toContain("renderSlot('sidebar.footer.action', { wide: true })")
    expect(shell).toContain("'conversation.session.header.actions': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("'conversation.session.header.utilities': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("'conversation.input.overlay': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("'conversation.input.dock': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("'conversation.composer.dock': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("'conversation.input.left': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("'conversation.input.right': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("'conversation.chat.assistant-actions': { kind: 'list', scope: 'session' }")
    expect(shell).toContain("renderSlot('conversation.chat.assistant-actions', { messageId })")
    expect(shell).toContain("'conversation.chat.turnTail': { kind: 'chain', scope: 'session' }")
    expect(shell).toContain("renderSlotChain('conversation.chat.turnTail', { turn, seq, openFile: conversation.openFile })")
    expect(shell).toContain("renderSlot('conversation.composer.dock'")
    expect(shell).toContain("renderSlot('conversation', {}, { only: 'dsh-work-conversation' })")
    expect(shell).toContain("document.querySelector('[data-dsh-standard-details]')")
    expect(shell).toContain("renderSlot('details', {})")
    expect(settings).toContain('<DshSettingsSection id="general"')
    expect(settings).toContain('<DshSettingsSection id="models"')
    expect(settings).toContain('<DshSettingsSection id="plugins"')
    expect(read('../views/agent/AgentNav.tsx')).toContain('data-dsh-sidebar-footer-actions')
    const conversation = read('../views/agent/AgentConversation.tsx')
    expect(conversation).toContain('data-dsh-session-header-actions')
    expect(conversation).toContain('data-dsh-session-header-utilities')
    expect(conversation).toContain('data-dsh-conversation-input-overlay')
    expect(conversation).toContain('conversation.trackInputTrigger')
    expect(conversation).toContain('conversation.arbitrateInputTrigger')
    expect(conversation).toContain('conversation.submitCommandClaim')
    expect(conversation).toContain("reserveLeadingSlash: slashMatch !== null")
    expect(conversation).toContain("data-active={officialInputMenuActive ? 'true' : undefined}")
    expect(conversation).toContain('data-dsh-conversation-input-dock')
    expect(conversation).toContain('data-dsh-conversation-composer-dock')
    expect(conversation).toContain('data-dsh-conversation-input-left')
    expect(conversation).toContain('data-dsh-conversation-input-right')
    expect(read('../views/agent/conversation/ConversationTurns.tsx')).toContain('data-dsh-assistant-message-id={message.dshMessageId}')
    expect(read('../views/agent/conversation/ConversationTurns.tsx')).toContain('data-dsh-closing-seq={message.dshClosingSeq}')
    expect(read('../views/agent/conversation/ConversationTurns.tsx')).toContain('data-dsh-produced-paths={JSON.stringify(dshProducedPaths)}')
    const agentShell = read('../views/agent/AgentShell.tsx')
    expect(agentShell).toContain('data-dsh-standard-details')
    expect(agentShell).toContain('setStandardDetailsOpen(opening)')
    expect(agentShell).toContain('hidden={standardDetailsOpen}')
    expect(read('../../../packages/dsh-work-shell/cordis.patch.yml')).toMatch(/id: ui-sidebar\n\s+disabled: true/)
    expect(read('../../../packages/dsh-work-shell/cordis.patch.yml')).toMatch(/id: ui-conversation\n\s+disabled: true/)
  })

  it('uses DSH Theme and Locale snapshots in the formal Client runtime', () => {
    const shell = read('../../../packages/dsh-work-shell/src/client/index.tsx')
    const host = read('./DshClientHost.tsx')
    const page = read('../views/agent/index.tsx')

    expect(shell).toContain("import { createDshThemePresenter }")
    expect(shell).toContain('const presenter = createDshThemePresenter(document)')
    expect(shell).toContain('presenter.present(snapshot)')
    expect(shell).toContain('presenter.dispose()')
    expect(shell).not.toContain('function applyTheme(')
    expect(host).toContain('themeSnapshot: ThemeSnapshot')
    expect(host).toContain('localeSnapshot: LocaleSnapshot')
    expect(page).toContain('dshClientHost?.themeSnapshot.preference')
    expect(page).toContain('dshClientHost?.themeSnapshot.active.colorScheme')
    expect(page).toContain('dshClientHost?.localeSnapshot.active')
    expect(page).toContain('if (!dshClientHost) localStorage.setItem')
  })

  it('lets rendered overlay children receive pointer input', () => {
    const css = read('./DshClientHost.module.scss')
    const conversationCss = read('../views/agent/agent.module.scss')

    expect(css).toContain('pointer-events: none')
    expect(css).toMatch(/> \* \{\s*pointer-events: auto/)
    expect(conversationCss).toContain(".composerInputOverlay:not([data-active='true'])")
    expect(conversationCss).toContain('pointer-events: none')
  })
})
