import type { AgentBlock, PlanStep } from './stream/types'
import { normalizePlanSteps } from './planState'

const PROCESS_BLOCK_TYPES = new Set(['thinking', 'tool', 'tool_result', 'plan', 'status', 'subtask', 'delegated_subtask'])
const PROCESS_ITEM_TYPES = new Set(['reasoning', 'dynamicToolCall', 'toolResult', 'plan', 'skill', 'subtask', 'collabAgentToolCall', 'subAgentActivity'])
const ACTION_BLOCK_TYPES = new Set(['error', 'confirm', 'user_input', 'action', 'file_change'])
const ACTION_ITEM_TYPES = new Set(['error', 'approval', 'userInput'])
const STRUCTURED_BLOCK_TYPES = new Set(['table', 'chart', 'image', 'json'])
const STANDALONE_MEDIA_BLOCK_TYPES = new Set(['image', 'audio'])
const HIDDEN_BLOCK_TYPES = new Set<string>()
const REFERENCE_CARD_BLOCK_TYPES = new Set(['web_sources'])

export interface AssistantProcessSummary {
  planSteps: number
  completedSteps: number
  currentStep: number | null
  toolCalls: number
  dataResults: number
  currentAction: string
  runningLabel: string
  completedLabel: string
}

function blockResultRole(block: AgentBlock) {
  return String(block.metadata?.result_role || '').trim()
}

function blockItemType(block: AgentBlock) {
  return String(block.metadata?.item_type || '').trim()
}

function compactText(value: unknown, max = 56) {
  const text = String(value || '').replace(/\s+/g, ' ').trim()
  if (!text) return ''
  return text.length > max ? `${text.slice(0, max).trimEnd()}…` : text
}

function planStepsFromBlock(block: AgentBlock): PlanStep[] {
  if (block.type !== 'plan' && blockItemType(block) !== 'plan') return []
  return normalizePlanSteps(block.content).map((step) => ({
    title: compactText(step.title),
    state: step.state
  }))
}

function latestPlanSteps(blocks: AgentBlock[]) {
  for (let index = blocks.length - 1; index >= 0; index -= 1) {
    const steps = planStepsFromBlock(blocks[index])
    if (steps.length > 0) return steps
  }
  return []
}

function toolCallKey(block: AgentBlock) {
  if (block.type !== 'tool' && blockItemType(block) !== 'dynamicToolCall') return ''
  return String(block.metadata?.tool_call_id || block.id || '').trim()
}

function isDataResult(block: AgentBlock) {
  if (blockItemType(block) === 'dataResult') return true
  return STRUCTURED_BLOCK_TYPES.has(block.type)
}

function toolAction(block: AgentBlock) {
  const content = compactText(block.content)
  if (!content) return ''
  const argumentsStart = content.search(/\s[\[{]/)
  return argumentsStart > 0 ? content.slice(0, argumentsStart).trim() : content
}

function currentAction(blocks: AgentBlock[], steps: PlanStep[]) {
  for (let index = blocks.length - 1; index >= 0; index -= 1) {
    const block = blocks[index]
    if (block.type === 'tool' && block.title === 'running') return toolAction(block)
    if (
      ['markdown', 'text', 'status'].includes(block.type) &&
      block.metadata?.answer_status !== 'accepted'
    ) {
      const text = compactText(block.content)
      if (text) return text
    }
  }

  const activeStep = steps.find((step) => step.state === 'running') || steps.find((step) => step.state === 'todo')
  if (activeStep?.title) return activeStep.title
  if (blocks.some((block) => block.type === 'thinking' || blockItemType(block) === 'reasoning')) return '正在思考'
  return ''
}

/**
 * Build a one-line process summary from blocks already generated by standard events.
 *
 * Keep this as UI-only aggregation. Do not add display-only fields to the protocol.
 * Deduplicate tool calls and data results by stable IDs; current action uses the last
 * visible running action.
 */
export function summarizeAssistantProcess(blocks: AgentBlock[], isRunning: boolean): AssistantProcessSummary {
  const steps = latestPlanSteps(blocks)
  const toolCalls = new Set(blocks.map(toolCallKey).filter(Boolean)).size
  const dataResults = new Set(blocks.filter(isDataResult).map((block) => block.id).filter(Boolean)).size
  const runningStepIndex = steps.findIndex((step) => step.state === 'running')
  const doneSteps = steps.filter((step) => step.state === 'done').length
  const failedSteps = steps.filter((step) => step.state === 'failed').length
  const skippedSteps = steps.filter((step) => step.state === 'skipped').length
  const interruptedSteps = steps.filter((step) => step.state === 'interrupted').length
  const currentStep = steps.length
    ? isRunning
      ? runningStepIndex >= 0
        ? runningStepIndex + 1
        : Math.min(doneSteps + 1, steps.length)
      : steps.length
    : null
  const action = isRunning ? currentAction(blocks, steps) : ''
  const runningParts = [
    currentStep ? `第 ${currentStep}/${steps.length} 步` : '',
    action
  ].filter(Boolean)
  const unfinishedSteps = steps.filter((step) => step.state === 'todo' || step.state === 'running').length
  const completedParts = [
    steps.length
      ? [
          `${doneSteps}/${steps.length} 已完成`,
          failedSteps ? `${failedSteps} 项失败` : '',
          skippedSteps ? `${skippedSteps} 项跳过` : '',
          interruptedSteps ? `${interruptedSteps} 项停止` : '',
          unfinishedSteps ? `${unfinishedSteps} 项未完成` : ''
        ].filter(Boolean).join(' · ')
      : '',
    toolCalls ? `${toolCalls} 次操作` : '',
    dataResults ? `${dataResults} 个结果` : ''
  ].filter(Boolean)

  return {
    planSteps: steps.length,
    completedSteps: doneSteps,
    currentStep,
    toolCalls,
    dataResults,
    currentAction: action,
    runningLabel: runningParts.join(' · '),
    completedLabel: completedParts.join(' · ')
  }
}

function isNarrativeBlock(block: AgentBlock) {
  return (
    ['text', 'markdown', 'agentMessage'].includes(block.type)
    || blockItemType(block) === 'agentMessage'
  )
}

function isStructuredResultBlock(block: AgentBlock) {
  if (isNarrativeBlock(block)) return false
  if (blockResultRole(block) === 'intermediate') return false
  return (
    STRUCTURED_BLOCK_TYPES.has(block.type)
    || blockItemType(block) === 'dataResult'
    || blockResultRole(block) === 'deliverable'
  )
}

function isActionBlock(block: AgentBlock) {
  return ACTION_BLOCK_TYPES.has(block.type) || ACTION_ITEM_TYPES.has(blockItemType(block))
}

/**
 * Split one assistant response into "process" and "final result".
 *
 * Only the exact canonical answer item can place narrative text in the result area.
 * All other narrative blocks remain process content. Structured deliverables and
 * user actions stay visible independently of the narrative answer.
 */
export function partitionAssistantBlocks(
  blocks: AgentBlock[],
  answer: { status?: string; itemId?: string | null } | null = null
) {
  const processBlocks: AgentBlock[] = []
  const resultBlocks: AgentBlock[] = []
  const answerItemId = answer?.status === 'accepted' ? String(answer.itemId || '').trim() : ''

  blocks.forEach((block) => {
    if (HIDDEN_BLOCK_TYPES.has(block.type) || block.metadata?.display === false) return
    const isCanonicalAnswer = Boolean(answerItemId) && String(block.id || '') === answerItemId && isNarrativeBlock(block)
    if (
      isCanonicalAnswer
      || isActionBlock(block)
      || REFERENCE_CARD_BLOCK_TYPES.has(block.type)
      || STANDALONE_MEDIA_BLOCK_TYPES.has(block.type)
      || isStructuredResultBlock(block)
    ) {
      resultBlocks.push(block)
      return
    }
    processBlocks.push(block)
  })

  return { processBlocks, resultBlocks }
}

function isReadableAgentMessage(block: AgentBlock) {
  return (
    ['text', 'markdown', 'agentMessage'].includes(block.type) &&
    String(block.content || '').trim().length > 0 &&
    (!block.metadata?.item_type || blockItemType(block) === 'agentMessage')
  )
}

function placeFinalAnswerBeforeMedia(blocks: AgentBlock[]) {
  const firstMediaIndex = blocks.findIndex((block) => STANDALONE_MEDIA_BLOCK_TYPES.has(block.type))
  if (firstMediaIndex < 0) return blocks
  const trailingAnswers = blocks
    .slice(firstMediaIndex)
    .filter(isReadableAgentMessage)
  if (!trailingAnswers.length) return blocks
  const movedIds = new Set(trailingAnswers.map((block) => block.id))
  return [
    ...blocks.slice(0, firstMediaIndex),
    ...trailingAnswers,
    ...blocks.slice(firstMediaIndex).filter((block) => !movedIds.has(block.id))
  ]
}

/**
 * Use only the server's canonical answer decision. A completed turn without
 * an accepted answer does not promote any narrative block into the result.
 */
export function partitionAssistantDisplayBlocks(
  blocks: AgentBlock[],
  completed: boolean,
  answer: { status?: string; itemId?: string | null } | null = null
) {
  const partitioned = partitionAssistantBlocks(blocks, answer)
  if (!completed) return partitioned
  return {
    ...partitioned,
    resultBlocks: placeFinalAnswerBeforeMedia(partitioned.resultBlocks)
  }
}

/**
 * Process summary already shows state, so avoid repeating it in expanded content.
 *
 * `status + skill` only signals which skill is active for the user.
 * Thinking, tool calls, and intermediate results stay available for expansion.
 * Plan details belong to the independent plan surface; the process header keeps only its summary.
 */
export function processDetailBlocks(blocks: AgentBlock[]) {
  return blocks.filter(
    (block) => block.type !== 'plan' && !(block.type === 'status' && blockItemType(block) === 'skill')
  )
}

/**
 * Default to expanded so the user can see the reasoning/process content without
 * an extra click. Manual user choice always takes priority.
 */
export function resolveProcessExpanded(manualExpanded: boolean | undefined, isRunning: boolean) {
  return manualExpanded ?? true
}

/**
 * When thinking is inside the process section, expand by default so the
 * reasoning is immediately visible. Standalone thinking blocks keep the
 * original behavior (expanded while running, collapsed after completion) via
 * resolveProcessExpanded.
 */
export function resolveThinkingExpanded(
  manualExpanded: boolean | undefined,
  isRunning: boolean,
  groupedProcess: boolean
) {
  return groupedProcess ? manualExpanded ?? true : resolveProcessExpanded(manualExpanded, isRunning)
}
